version: '2'

services:
  db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     networks:
       - net-spring-db
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: database-for-bittrex
       MYSQL_USER: bittrex-market-user
       MYSQL_PASSWORD: bittrex-market-pass
       MYSQL_ROOT_HOST: 0.0.0.0
  springapp:
     ports:
       - "8080:8080"
     depends_on:
       - db
     image: java:8-jdk
     networks:
       - net-spring-db
     build:
      context: .
      dockerfile: Dockerfile


networks:
  net-spring-db:
    driver: bridge
